### ISSUE TITLE
Option to connect without changing auth method does not work

### ISSUE THREAD

**Issue by TubsDK** [MSOpenTech/moodle-auth_oidc#2]
We have tested the option of connecting a user to Office 365 without changing the auth method - but have experienced some issues. 

The ucp.php expects that a record exists in local_o365_token to show a correct Office 365 connection status. 

But the auth flow in authcode.php always creates a record in auth_oidc_token . 

This means that the Office 365 connection will never be view correctly. Furthermore this causes an issue if the user once again, tries to connect to Office 365 using the "Connect to Office 365". Since a record now exists in auth_oidc_token, the lines 190 authcode.php will now switch the user to OIDC authentication, regardless if OIDC has been disabled for the site.

**Comment by jamesmcq** [comment]
Hi @TubsDK,

I've released a fix for the second issue you mentioned - being able to switch OpenID Connect even if it's disabled. Thanks for the report!

Regarding your first issue - auth_oidc_token stores tokens only related to OpenID Connect, it doesn't contain tokens for any Office365-specific resources, which are stored in local_o365_token. This is why that checks local_o365_token. When a user connects, Moodle should handle that event by fetching additional Office365-specific tokens for that user. The latest release fixes a number of issues around fetching tokens so can you upgrade and let me know if this issue is still present? 

Thanks!
- James

**Comment by jamesmcq** [comment]
Going to close this issue, if your first issue is still causing trouble please create a new issue.
